#pragma once
#define GLM_FORCE_INLINE
#define GLM_FORCE_CXX14
#define GLM_FORCE_MESSAGES
#define GLM_FORCE_SWIZZLE
#define GLM_FORCE_EXPLICIT_CTOR
#define GLM_PRECISION_MEDIUMP_UINT
#define GLM_PRECISION_MEDIUMP_INT
#define GLM_PRECISION_MEDIUMP_FLOAT
#define GLM_PRECISION_MEDIUMP_DOUBLE
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <glm/mat3x3.hpp>
#include <glm/mat4x4.hpp>
#include <glm/vec2.hpp>
#include <glm/vec3.hpp>
