#!/usr/bin/env ruby
require 'fileutils'

include_dirs = ["app/src", "lib/src", "lib/inc"]

command = "cppcheck --xml --xml-version=2 --force --enable=all --suppress=missingIncludeSystem --std=c++11 --quiet"
output_dir = "out/cppcheck"

include_dir_list = include_dirs.collect{|i| "-I#{i}"}.join(" ")

FileUtils.mkdir_p(output_dir) unless File.directory?(output_dir)

File.open("#{output_dir}/result.xml", "w:UTF-8") {|f|
    IO.popen("#{command} #{include_dir_list} app lisb 2>&1") {|io|
        f << io.read
    }
}
